###############################################################################
# Dockerfile
# 27/06/2025 - Luca Volpi - lvolpi@cvservicesconsulting.com
#
# Docker file per immagine di base di mySql Server
###############################################################################

FROM mysql:8.0